"""empty message

Revision ID: 3f817193ab03
Revises: 
Create Date: 2019-11-22 16:56:19.608703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f817193ab03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=13), nullable=True),
    sa.Column('stock_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('WKN', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('provision', sa.Float(), nullable=False),
    sa.Column('dividend_tax', sa.Float(), nullable=True),
    sa.Column('church_tax', sa.Float(), nullable=True),
    sa.Column('soli_tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('courtage', sa.Float(), nullable=True),
    sa.Column('exchange_provision', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('closed', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction')),
    sa.UniqueConstraint('order_number', name=op.f('uq_transaction_order_number'))
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name=op.f('fk_user_transaction_id_transaction')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('transaction')
    # ### end Alembic commands ###
