"""empty message

Revision ID: fd89419b6801
Revises: 
Create Date: 2019-11-24 18:26:03.393943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd89419b6801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=13), nullable=True),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('stock_name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('WKN', sa.String(length=6), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('provision', sa.Float(), nullable=False),
    sa.Column('dividend_tax', sa.Float(), nullable=True),
    sa.Column('church_tax', sa.Float(), nullable=True),
    sa.Column('soli_tax', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('courtage', sa.Float(), nullable=True),
    sa.Column('exchange_provision', sa.Float(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('closed', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('filename', name=op.f('uq_transactions_filename'))
    )
    op.create_table('user_transaction',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_user_transaction_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user_transaction'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_transaction')
    op.drop_table('transactions')
    # ### end Alembic commands ###
